id = "oc-2-theme"
name = "OC-2 Theme"
version = "0.0.1"
schema_version = 1
authors = ["nstlgy"]
description = "A light and dark Zed theme based on the OC-2 color palette."
repository = "https://github.com/nstlgy/oc-2-theme"
